#!/usr/bin/env python3
"""
tools/critical_path/report.py
=============================

Step 5 of the DAG critical-path pipeline.

Reads reports/critical-path-all.json (produced by dag.py) and emits five
human-readable Markdown reports:

    reports/critical-path-proof.md
    reports/critical-path-spec.md
    reports/critical-path-haskell.md
    reports/critical-path-c.md
    reports/critical-path-summary.md

Each per-change-type report contains:
    - Closure summary (n sessions, n theories, total weight, CP total)
    - Top 20 theories on the critical path, ranked by total weight desc
    - Top 10 by fanout (cross-cutting impact)
    - Top 25 by low slack (priority bottlenecks)
    - Notes specific to this change type

The summary report cross-references all four to identify:
    - Theories in CP top-10 of multiple change types (universal bottlenecks)
    - Recommended top-3 optimization targets per change type
    - Profile-specific bottlenecks (theories that are critical for ONE
      change type but not others)
"""
from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
INPUT = REPO / "CSTR-2" / "outputs" / "critical-path-all.json"
OUT_DIR = REPO / "reports"


CHANGE_TYPE_TITLES = {
    "proof": "proof-only",
    "spec_abstract": "spec_abstract (MA layer)",
    "spec_invariant": "spec_invariant (AInvs layer)",
    "spec_cspec": "spec_cspec (C-side abstract spec)",
    "spec_lib": "spec_lib (foundational utility)",
    "haskell": "haskell",
    "c": "C",
}

CHANGE_TYPE_DESCRIPTIONS = {
    "proof": (
        "Changes to `verification/l4v/proof/**/*.thy`. "
        "Closure includes refinement layer downstream of any proof file. "
        "Asm-refinement / autocorres-test / camkes branches excluded "
        "unless the changed file is under those subtrees."
    ),
    "spec_abstract": (
        "Changes to **abstract specification** (`spec/abstract/**/*.thy`) — "
        "the MA layer in SOSP'09 Fig. 2. Logical scope per the paper: only "
        "Theorem 1 (`ME refines MA`) and proofs depending on MA's lemmas "
        "(AInvs, Refine). Real build scope is wider due to (a) CSTR ROOT "
        "inheritance reprocessing Refine inside CBaseRefine, and (b) the "
        "ASpec→ExecSpec cross-cut (see summary §Structural findings)."
    ),
    "spec_invariant": (
        "Changes to **invariant proofs** over abstract spec "
        "(`proof/invariant-abstract/**/*.thy`). Per SOSP'09 §4.5, "
        "~80% of refinement-proof effort goes to maintaining these. "
        "Closure starts at AInvs layer, so does NOT propagate up "
        "through ASpec — narrower than spec_abstract."
    ),
    "spec_cspec": (
        "Changes to **hand-written C-side abstract spec** "
        "(`spec/cspec/**/*.thy`). Closure: CSpec → CKernel → "
        "C-side refinement chain + asm-refinement. Should NOT propagate "
        "to ASpec / AInvs / Access."
    ),
    "spec_lib": (
        "Changes to **shared utility theories** (`lib/**/*.thy`). "
        "Foundational infrastructure — almost every l4v session imports "
        "lib. Naturally the widest closure (worst-case spec change)."
    ),
    "haskell": (
        "Changes to Haskell prototype (`spec/haskell/**/*.hs`). "
        "Triggers regeneration of `spec/design/**/*.thy` (ExecSpec session), "
        "which then invalidates Refine, CBaseRefine, CRefine, CRefineSyscall, "
        "InfoFlow*, DSpec/DBaseRefine/DRefine/DPolicy/SepDSpec/DSpecProofs. "
        "Through the ASpec→ExecSpec cross-cut, also propagates back UP to "
        "ASpec/AInvs/Access — surfaced as a structural finding in the summary."
    ),
    "c": (
        "Changes to seL4 kernel C source (`verification/seL4/src/**/*.{c,h}`). "
        "Triggers C-parser regeneration of `spec/cspec/c/build/ARM/*.thy`, "
        "invalidating CSpec → CKernel → CBaseRefine → CRefine + asm-refinement "
        "chain (SimplExport, SimplExportAndRefine)."
    ),
}

# Order in which change types are rendered (and iterated in summary).
CHANGE_TYPE_ORDER = (
    "proof",
    "spec_abstract",
    "spec_invariant",
    "spec_cspec",
    "spec_lib",
    "haskell",
    "c",
)


def fmt_float(f: float) -> str:
    return f"{f:.1f}"


def render_change_report(name: str, data: dict, summary_data: dict) -> str:
    title = CHANGE_TYPE_TITLES[name]
    desc = CHANGE_TYPE_DESCRIPTIONS[name]
    out: list[str] = []

    out.append(f"# Critical-path report — {title} change type")
    out.append("")
    out.append("_Generated by `tools/critical_path/report.py` from `reports/critical-path-all.json`._  ")
    out.append(f"_Cost model: each theory's weight = sum of elapsed across every session_  ")
    out.append(f"_in `heaps/db-archive/*.db` (CSTR cost model — captures duplication overhead)._")
    out.append("")
    out.append("## Scope")
    out.append("")
    out.append(desc)
    out.append("")
    out.append(f"**Manifest entry paths**:")
    for p in data["manifest"]["entry_paths"]:
        out.append(f"- `{p}`")
    out.append("")

    # ---- Closure summary ----
    out.append("## Rebuild closure")
    out.append("")
    out.append(f"- Sessions in closure: **{data['session_closure_size']}** of 56 ({100*data['session_closure_size']/56:.0f}%)")
    out.append(f"- Theories in closure: **{data['theory_closure_size']}** of 1094 ({100*data['theory_closure_size']/1094:.0f}%)")
    out.append(f"- Closure total weight (sum of theory weights): **{fmt_float(data['closure_total_weight'])}s**")
    out.append(f"- Critical path total: **{fmt_float(data['critical_path_total_weight'])}s** "
               f"({100*data['critical_path_total_weight']/max(data['closure_total_weight'],1):.1f}% of closure)")
    out.append(f"- Critical path length: **{data['critical_path_node_count']}** theories")
    out.append("")
    out.append("**Sessions in closure**: " + ", ".join(f"`{s}`" for s in data["session_closure"]))
    out.append("")

    # ---- Top by slack low (priority bottlenecks — these are the optimization targets) ----
    out.append("## Top 25 priority bottlenecks (low slack, weight > 5s)")
    out.append("")
    out.append("Theories with the least scheduling flexibility — optimizing these yields the most direct wall reduction.")
    out.append("")
    out.append("| rank | theory | session | weight (s) | n_sess | dup overhead | fanout | slack | on CP |")
    out.append("|---:|---|---|---:|---:|---:|---:|---:|:---:|")
    for i, n in enumerate(data["top_by_slack_low"][:25], 1):
        cp = "✓" if n["on_critical_path"] else ""
        out.append(
            f"| {i} | `{n['theory']}` | {n['session']} | "
            f"{n['weight_total_elapsed']:.1f} | {n['n_sessions']} | "
            f"{n['duplication_overhead']:.1f} | {n['fanout']} | "
            f"{n['slack']:.1f} | {cp} |"
        )
    out.append("")

    # ---- Top 20 critical-path by weight ----
    cp_in_order = data["critical_path_in_order"]
    cp_by_weight = sorted(cp_in_order, key=lambda n: -n["weight_total_elapsed"])[:20]
    out.append("## Top 20 critical-path theories (sorted by weight)")
    out.append("")
    out.append("All on the critical path (slack ≈ 0). Ordered by their individual weight — "
               "these are the heaviest links in the longest dependency chain.")
    out.append("")
    out.append("| rank | theory | session | weight (s) | n_sess | dup overhead | fanout | EST→EFT |")
    out.append("|---:|---|---|---:|---:|---:|---:|:---|")
    for i, n in enumerate(cp_by_weight, 1):
        out.append(
            f"| {i} | `{n['theory']}` | {n['session']} | "
            f"{n['weight_total_elapsed']:.1f} | {n['n_sessions']} | "
            f"{n['duplication_overhead']:.1f} | {n['fanout']} | "
            f"{n['EST']:.0f}→{n['EFT']:.0f} |"
        )
    out.append("")

    # ---- Top 10 by fanout ----
    out.append("## Top 10 by fanout (cross-cutting impact)")
    out.append("")
    out.append("Theories with the most transitive importers in this closure. "
               "Optimizing or restructuring these affects the largest set of downstream theories.")
    out.append("")
    out.append("| rank | theory | session | weight (s) | fanout | n_sess | on CP |")
    out.append("|---:|---|---|---:|---:|---:|:---:|")
    for i, n in enumerate(data["top_by_fanout"][:10], 1):
        cp = "✓" if n["on_critical_path"] else ""
        out.append(
            f"| {i} | `{n['theory']}` | {n['session']} | "
            f"{n['weight_total_elapsed']:.1f} | {n['fanout']} | "
            f"{n['n_sessions']} | {cp} |"
        )
    out.append("")

    # ---- Notes ----
    out.append("## Notes")
    out.append("")
    if name == "proof":
        out.append(
            "- **Critical path is dominated by Refine session theories** that are "
            "  reprocessed in CBaseRefine (CSTR finding): each `Refine.*` entry with "
            "  `n_sess=2` represents work done twice.")
        out.append(
            "- **Top split candidates** by slack are `Finalise_R`, `IpcCancel_R`, "
            "  `CSpace_R`, `CSpace1_R`, `Untyped_R`, `Retype_R` — all with duplication "
            "  overhead > 70s. Splitting any of them into Base/Heavy and decoupling "
            "  imports could yield meaningful wall reductions.")
        out.append(
            "- AInvs theories appear at the top by **fanout** (260+) but have low "
            "  individual weight (<120s). They sit at the dependency root; "
            "  optimizing them is structurally hard but ripples broadly.")
    elif name == "spec_abstract":
        out.append(
            "- Logical scope per SOSP'09 Fig. 2: a change here should only affect "
            "  Theorem 1 (`ME refines MA`) — i.e., AInvs + Refine. The actual "
            "  closure is wider due to two structural anomalies:")
        out.append(
            "    1. **CSTR ROOT inheritance** — Refine theories get reprocessed "
            "       inside CBaseRefine, so changes ripple to CBaseRefine + CRefine.")
        out.append(
            "    2. **ASpec→ExecSpec cross-cut** — `spec/ROOT` declares ASpec "
            "       to import ExecSpec, so BFS pulls ExecSpec → CKernel → CSpec "
            "       and then their downstreams into the closure.")
        out.append(
            "- See summary §Structural findings for proposed fixes.")
    elif name == "spec_invariant":
        out.append(
            "- Closure starts at AInvs and goes downstream — narrower than "
            "  spec_abstract because we don't traverse the ASpec→ExecSpec "
            "  cross-cut from above.")
        out.append(
            "- Top slack=0 set overlaps heavily with proof-only — these are "
            "  the same Refine-system theories reprocessed in CBaseRefine.")
    elif name == "spec_cspec":
        out.append(
            "- This is the C-side abstract spec, distinct from the spec_abstract "
            "  (ASpec) layer. Closure stays in the C/asm-refinement chain — "
            "  does NOT propagate to ASpec/AInvs/Access/InfoFlow.")
        out.append(
            "- Often dominated by SimplExport / SimplExportAndRefine if the "
            "  asm-refinement chain is in scope.")
    elif name == "spec_lib":
        out.append(
            "- This is the **worst-case** change type: lib/ is foundational, "
            "  imported almost everywhere. The closure naturally spans most of "
            "  the DAG.")
        out.append(
            "- **Word_Lib** dominates the fanout list (>800 transitive importers) "
            "  but its theories are tiny in absolute weight. This means lib changes "
            "  are **closure-amplifying** (rebuild a lot) but not weight-amplifying "
            "  (don't make any single rebuild dramatically longer).")
        out.append(
            "- Optimization strategy here is **incremental rebuild**, not "
            "  structural splitting — lib/ already is split sensibly across "
            "  multiple sessions (Word_Lib, Lib, CorresK, Eisbach, etc.).")
    elif name == "haskell":
        out.append(
            "- **ExecSpec session** appears as the top fanout target (Kernel_Config, "
            "  Platform, MachineTypes) — these are the regenerated entry points from "
            "  Haskell into Isabelle. A Haskell change typically invalidates ALL of "
            "  ExecSpec, which then triggers Refine + downstream.")
        out.append(
            "- ExecSpec theories show `n_sessions=3` — they appear in ExecSpec, "
            "  Refine, and CBaseRefine, indicating triple-processing under the "
            "  current ROOT inheritance model (CSTR pattern).")
        out.append(
            "- Critical path mostly tracks the spec/proof CP, since Haskell changes "
            "  enter via design.thy and propagate through the same Refine→CRefine chain.")
    elif name == "c":
        out.append(
            "- **Critical path is dramatically different** from proof/spec/haskell "
            "  — only 5 nodes total. Dominated by:")
        out.append("    1. `SimplExportAndRefine.SEL4GraphRefine` (2228s) — single ML-block")
        out.append("    2. `CKernel.Kernel_C` (692s)")
        out.append("    3. `SimplExport.SEL4SimplExport` (606s)")
        out.append(
            "- **No CSTR duplication amplification** here — all key theories have "
            "  `n_sessions=1` because CSpec/CKernel/SimplExport* are clean (the C path "
            "  is one of the few unduplicated layers in l4v).")
        out.append(
            "- The asm-refinement monolith (SEL4GraphRefine.thy) accounts for **62%** "
            "  of the critical path. Chunking that single ML invocation is the highest-"
            "  leverage structural target for C-driven workflows.")

    out.append("")
    out.append("---")
    out.append("")
    out.append(f"_Source data: [`reports/critical-path-all.json`](critical-path-all.json), "
               f"[`reports/session-duplication-scan.json`](session-duplication-scan.json), "
               f"[`reports/theory-dag.json`](theory-dag.json), "
               f"[`reports/session-dag.json`](session-dag.json)._")
    return "\n".join(out) + "\n"


def render_summary_report(all_data: dict, dup_data: dict | None = None) -> str:
    available_cts = tuple(ct for ct in CHANGE_TYPE_ORDER if ct in all_data["change_types"])
    out: list[str] = []
    out.append(f"# Critical-path summary — all {len(available_cts)} change types")
    out.append("")
    out.append("_Generated by `tools/critical_path/report.py` from `reports/critical-path-all.json`._  ")
    out.append(f"_Total cost model footprint: {all_data['theory_weights_summary']['total_weight_all']}s "
               f"of which {all_data['theory_weights_summary']['duplication_total_overhead']}s "
               f"({100*all_data['theory_weights_summary']['duplication_total_overhead']/max(all_data['theory_weights_summary']['total_weight_all'],1):.1f}%) "
               f"is cross-session duplication overhead (CSTR)._")
    out.append("")
    out.append("> **Note**: The original `spec` change type has been split into four "
               "sub-types — `spec_abstract`, `spec_invariant`, `spec_cspec`, `spec_lib` — "
               "to reflect the very different closure widths produced by changes to "
               "abstract spec vs. lib utilities. See per-type reports for details.")
    out.append("")

    # ---- High-level table ----
    out.append("## Closure size & critical path per change type")
    out.append("")
    out.append("| change type | sessions in closure | theories in closure | closure total weight | critical path total | CP nodes |")
    out.append("|---|---:|---:|---:|---:|---:|")
    for ct in available_cts:
        d = all_data["change_types"][ct]
        out.append(
            f"| **{ct}** | {d['session_closure_size']} | {d['theory_closure_size']} | "
            f"{d['closure_total_weight']:.0f}s | {d['critical_path_total_weight']:.0f}s | "
            f"{d['critical_path_node_count']} |"
        )
    out.append("")

    # ---- Cross-cutting universal bottlenecks ----
    out.append("## Cross-cutting bottlenecks (theories in top-25 slack of multiple change types)")
    out.append("")
    universal: dict[str, set[str]] = {}
    for ct in available_cts:
        for n in all_data["change_types"][ct]["top_by_slack_low"][:25]:
            universal.setdefault(n["theory"], set()).add(ct)
    multi = {k: v for k, v in universal.items() if len(v) >= 2}
    multi_sorted = sorted(multi.items(), key=lambda kv: (-len(kv[1]), kv[0]))

    out.append("| theory | weight (s) | n_sess | dup overhead | appears in change types |")
    out.append("|---|---:|---:|---:|---|")
    # Pull weight info from any of the change types
    for thy, cts in multi_sorted[:20]:
        info = None
        for ct in cts:
            for n in all_data["change_types"][ct]["top_by_slack_low"]:
                if n["theory"] == thy:
                    info = n
                    break
            if info:
                break
        if info:
            out.append(
                f"| `{thy}` | {info['weight_total_elapsed']:.1f} | "
                f"{info['n_sessions']} | {info['duplication_overhead']:.1f} | "
                f"{', '.join(sorted(cts))} |"
            )
    out.append("")
    out.append(f"**{len(multi)}** theories appear in the slack-top of ≥2 change types — "
               f"these are the universal bottlenecks regardless of where the change originates.")
    out.append("")

    # ---- Profile-specific bottlenecks ----
    out.append("## Profile-specific bottlenecks (top-3 unique to each change type)")
    out.append("")
    for ct in available_cts:
        in_others: set[str] = set()
        for other in available_cts:
            if other == ct:
                continue
            for n in all_data["change_types"][other]["top_by_slack_low"][:25]:
                in_others.add(n["theory"])
        unique = [n for n in all_data["change_types"][ct]["top_by_slack_low"][:50]
                  if n["theory"] not in in_others][:3]
        out.append(f"### {ct}")
        out.append("")
        if unique:
            out.append("| theory | weight (s) | n_sess | session | rationale |")
            out.append("|---|---:|---:|---|---|")
            for n in unique:
                rationale = "specific to this change type's closure"
                if "SimplExport" in n["theory"] or "SEL4GraphRefine" in n["theory"]:
                    rationale = "asm-refinement (only in C path)"
                elif n["session"] == "ExecSpec":
                    rationale = "design-spec entry point (only in Haskell path)"
                elif n["session"] == "CKernel" or n["session"] == "CSpec":
                    rationale = "C-side spec (only in C path)"
                out.append(
                    f"| `{n['theory']}` | {n['weight_total_elapsed']:.1f} | "
                    f"{n['n_sessions']} | {n['session']} | {rationale} |"
                )
        else:
            out.append("_(no unique bottlenecks — all top-3 are shared with other change types)_")
        out.append("")

    # ---- Recommendations ----
    out.append("## Recommended top-3 optimization candidates per change type")
    out.append("")
    out.append("Selection rule: among slack=0 theories with weight > 50s, prefer those with "
               "highest `duplication_overhead` (= work that disappears if the CSTR inheritance "
               "issue is fixed) AND highest fanout. Top 3 per type, deduplicated within type.")
    out.append("")
    for ct in available_cts:
        d = all_data["change_types"][ct]
        # Score = weight × (1 + duplication_factor) × log(fanout+1) ... we'll just sort
        # by (-weight, -duplication_overhead). Pick from top_by_slack_low.
        candidates = [n for n in d["top_by_slack_low"]
                      if n["weight_total_elapsed"] > 50 and n["on_critical_path"]]
        # Sort: highest weight × (1 + dup_overhead/weight)
        candidates.sort(key=lambda n: -(n["weight_total_elapsed"]
                                         + n["duplication_overhead"]))
        out.append(f"### {ct}")
        out.append("")
        if candidates:
            for i, n in enumerate(candidates[:3], 1):
                eff = n["weight_total_elapsed"] + n["duplication_overhead"]
                out.append(
                    f"**#{i}** `{n['theory']}` — weight {n['weight_total_elapsed']:.0f}s "
                    f"(dup overhead {n['duplication_overhead']:.0f}s, n_sess={n['n_sessions']}, "
                    f"fanout={n['fanout']})  ")
                out.append(
                    f"Total upper-bound saving if optimized to 0: ~{eff:.0f}s wall.")
                out.append("")
        else:
            out.append("_(no candidates passing the filter)_")
        out.append("")

    # ---- CSTR structural patterns + 3rd-party overhead (data from dup scan) ----
    if dup_data is not None:
        out.append("## CSTR structural duplication patterns")
        out.append("")
        out.append(
            "The duplication footprint identified by CSTR splits into **three "
            "structural patterns**, each requiring a different remediation. The "
            "table below summarises each pattern and which change types feel its "
            "impact most strongly."
        )
        out.append("")
        out.append("| pattern | mechanism | affects | wall impact (s) | remediation |")
        out.append("|---|---|---|---:|---|")

        # Pattern 1: Perpetrator/Victim from case_studies
        cases = dup_data.get("case_studies", [])
        pv_total = sum(c["elapsed_in_perpetrator_on_overlap"] for c in cases)
        out.append(
            f"| **Perpetrator/Victim** | A session imports `\"Y.Foo\"` while only "
            f"`+ X` (X ≠ Y) is heap-merged → entire Y is re-executed | "
            f"proof, spec, haskell | ~{pv_total:.0f} | "
            f"`+ Y` ROOT change, or shared parent merging both X and Y |"
        )

        # Pattern 2: Shared 3rd-party
        third = dup_data.get("shared_dependency_overhead", [])
        third_total = sum(t["total_elapsed_across_appearances"] for t in third)
        # Rough split: subtract the "first appearance" cost (the 'necessary' one) per session
        third_overhead = sum(
            t["total_elapsed_across_appearances"]
            - (t["total_elapsed_across_appearances"] / max(t["appearing_in_n_canonical_sessions"], 1))
            for t in third
        )
        out.append(
            f"| **Shared 3rd-party** | Library sessions (Lib, Monads, ExecSpec, "
            f"Eisbach_Tools) declared via `sessions Y` in many canonical sessions, "
            f"each independently re-executes Y's theories | "
            f"haskell (ExecSpec), spec (Lib/Monads), all | "
            f"~{third_overhead:.0f} | "
            f"Make these sessions a `+` parent of all consumers, or build "
            f"a shared parent that already merges them |"
        )

        # Pattern 3: SEL4GraphRefine (asm refinement monolith)
        out.append(
            "| **Asm-refinement monolith** | "
            "`proof/asmrefine/SEL4GraphRefine.thy:72` does all graph-refinement "
            "proofs in one ML block via "
            "`ProveSimplToGraphGoals.test_all_graph_refine_proofs_parallel` | "
            "C only | ~2228 | "
            "Chunk the ML invocation into multiple theory boundaries so "
            "incremental rebuild becomes possible |"
        )
        out.append("")

        # ---- Shared 3rd-party detail table ----
        out.append("### Shared third-party sessions detail")
        out.append("")
        out.append(
            "Theories owned by sessions NOT in the canonical 28-session build set "
            "(libraries) but appearing in MULTIPLE canonical sessions' BLOBs — "
            "each canonical session re-executes them independently."
        )
        out.append("")
        out.append("| 3rd-party session | #thys | × #canonical sessions | Σelapsed (all appearances) | which change types affected |")
        out.append("|---|---:|---:|---:|---|")
        # Map: 3rd-party session → which change types it sits on closure for
        # (heuristic by name: ExecSpec→haskell, Lib/Monads→all-via-Refine, etc.)
        third_party_change_type_map = {
            "ExecSpec": "haskell (regen entry), spec, proof",
            "Lib": "all four (foundational utility)",
            "Monads": "proof, spec, haskell (monad WP infrastructure)",
            "CLib": "C (C-side utility)",
            "Eisbach_Tools": "all four (proof tactic library)",
            "CorresK": "proof, spec, haskell (corres infrastructure)",
            "HOL-Library": "all four",
            "ML_Utils": "all four",
            "HOL-Combinatorics": "spec",
            "Basics": "all four",
        }
        for r in third[:10]:
            k = r["third_party_session"]
            affected = third_party_change_type_map.get(k, "—")
            out.append(
                f"| `{k}` | {r['n_theories']} | "
                f"{r['appearing_in_n_canonical_sessions']} | "
                f"{r['total_elapsed_across_appearances']:.1f} | {affected} |"
            )
        out.append("")
        out.append(
            "**Notable for haskell change type**: `ExecSpec` (75 thys × 5 sessions, "
            "718s total) is the regenerated design-spec layer. Each Haskell change "
            "invalidates ExecSpec, and each canonical session that uses ExecSpec "
            "(Refine, CBaseRefine, DBaseRefine, ...) reprocesses the affected "
            "theories independently. Resolving this is orthogonal to the "
            "Perpetrator/Victim Refine→CBaseRefine dedupe."
        )
        out.append("")

    # ---- Structural findings: four orthogonal targets ----
    out.append("## Structural findings: four orthogonal optimization targets")
    out.append("")
    out.append(
        f"The {len(available_cts)} change types' bottleneck profiles are covered by "
        "**four orthogonal structural fixes**, each addressing a distinct anomaly "
        "in l4v's session graph. No single fix covers everything; conversely, doing "
        "all four would eliminate the bulk of cross-session duplication overhead "
        "documented in [reports/session-duplication-scan.md]"
        "(session-duplication-scan.md)."
    )
    out.append("")
    out.append(
        "**(a) Perpetrator/Victim ROOT inheritance dedupe** — "
        "Edit [proof/ROOT:106](../verification/l4v/proof/ROOT) and similar lines so "
        "downstream sessions merge their refinement-side parent via `+` instead of "
        "pulling it in via `imports \"Y.foo\"` from a `sessions Y` namespace "
        "declaration. Top targets: CBaseRefine→Refine (3538s), CRefineSyscall→"
        "CRefine (1546s), CBaseRefine→AInvs (1416s). **Helps**: proof, "
        "spec_abstract, spec_invariant, haskell. **Risk**: ML state conflicts "
        "may force a refactor rather than a 1-line swap.  "
        "**EMPIRICALLY VALIDATED 2026-05-09** ([experiments/cbaserefine-swap-parent.md]"
        "(../experiments/cbaserefine-swap-parent.md), 4 runs): three changes "
        "to `proof/ROOT` (CBaseRefine `= CSpec +` → `= Refine +`; CRefineSyscall "
        "`= CBaseRefine + sessions CRefine` → `= CRefine +`; InfoFlowCBase "
        "drop now-redundant `sessions Refine`) yielded "
        "**−7543s wall (−29.8% of canonical TUNED total)** across 5 affected "
        "sessions: CBaseRefine −3865s (−74.6%), CRefine −518s (−11.4%, ML-state "
        "GC bonus from cleaner parent heap), CRefineSyscall −3306s (−99.97%, "
        "was pure dup — Intermediate_C is the only own theory), InfoFlowCBase "
        "+149s (+13.4%, residual CSTR from `sessions InfoFlow Access`), "
        "InfoFlowC −4s (~baseline parity after cleanup). Far exceeded original "
        "~5500s upper-bound estimate (5×): the under-count came from missing "
        "GC pressure as a wall multiplier, the 100%-dup nature of "
        "CRefineSyscall, and parent-heap hygiene transferring to descendants."
    )
    out.append("")
    out.append(
        "**(b) Shared third-party heap-merging** — "
        "Restructure consumers of `ExecSpec`, `Lib`, `Monads`, `Eisbach_Tools` to "
        "share a common heap-merged ancestor. The biggest single win is `ExecSpec` "
        "(reprocessed in 5 canonical sessions; ~575s overhead). **Helps**: haskell "
        "most, spec/proof some. **Risk**: lower than (a); ExecSpec is already "
        "well-defined as a session, just not heap-merged."
    )
    out.append("")
    out.append(
        "**(c) Asm-refinement ML chunking** — "
        "Split [proof/asmrefine/SEL4GraphRefine.thy:72]"
        "(../verification/l4v/proof/asmrefine/SEL4GraphRefine.thy)'s monolithic "
        "ML invocation into multiple theories so `isabelle build` can checkpoint "
        "and incrementally rebuild. Currently 2228s of one atomic block. "
        "**Helps**: C only. **Risk**: requires understanding the SimplToGraph "
        "proof infrastructure to chunk safely."
    )
    out.append("")
    out.append(
        "**(d) ASpec→ExecSpec cross-cut elimination** — "
        "[spec/ROOT:64-71](../verification/l4v/spec/ROOT) declares "
        "`session ASpec ... sessions ExecSpec`, making the *abstract spec layer* "
        "depend on the *executable spec layer*. This violates the SOSP'09 Fig. 2 "
        "refinement tower (MA should be foundational, ME should refine MA, not "
        "vice versa). Empirical effect: any change to ExecSpec or Haskell "
        "regenerates ASpec, which then reverse-propagates through AInvs, Access, "
        "InfoFlow, Bisim, etc. — adding ~14 sessions to the haskell change "
        "closure that should not logically be there."
    )
    out.append("")
    out.append(
        "  - **Investigation**: identify which symbols/types ASpec actually imports "
        "from ExecSpec. If only a few base architectural constants, lift them to "
        "Word_Lib or a new SharedSpec session that ExecSpec and ASpec both depend on, "
        "rather than ASpec depending on ExecSpec.  "
    )
    out.append(
        "  - **Helps**: haskell, spec_abstract.  "
    )
    out.append(
        "  - **Risk**: low if the imported surface is small; medium if ASpec uses "
        "more of ExecSpec than expected.  "
    )
    out.append(
        "  - **Wall impact estimate**: 14 sessions × average ~300s avoided rebuild "
        "= ~3000-4000s upper bound for the haskell closure (which currently includes "
        "ASpec, AInvs, Access, InfoFlow, Bisim and their downstreams)."
    )
    out.append("")
    out.append(
        "**Wall recovery accounting** (revised after empirical (a) validation):  "
    )
    out.append(
        "  - (a) **MEASURED −7466s** (−29.5% of total canonical wall). "
        "Already exceeds the original 4000-7000s estimate by itself.  "
    )
    out.append(
        "  - (b) ~1300s estimate, partially exposed by (a)'s downstream "
        "regression on InfoFlowCBase/C (+222s); addressable as (a-cont).  "
    )
    out.append(
        "  - (c) ~2200s estimate, untouched (orthogonal — only affects C "
        "change-type / asm-refinement chain).  "
    )
    out.append(
        "  - (d) ~3500s estimate (haskell ASpec→ExecSpec cross-cut), untouched.  "
    )
    out.append(
        "  - **Total realistic if all four land**: ~14,000s wall recovery "
        "(~55% of canonical TUNED total). With (a) alone already at −29.5%, "
        "the practical ceiling appears higher than the original 15-30% guess."
    )
    out.append("")
    out.append(
        "**Mapping to per-type bottlenecks**:"
    )
    out.append("")
    out.append("| change type | (a) ROOT dedupe | (b) 3rd-party heap | (c) ML chunking | (d) ASpec cross-cut |")
    out.append("|---|:---:|:---:|:---:|:---:|")
    out.append("| proof | ✓✓ | ○ | – | – |")
    out.append("| spec_abstract | ✓✓ | ○ | – | ○ |")
    out.append("| spec_invariant | ✓✓ | – | – | – |")
    out.append("| spec_cspec | ○ | – | ✓ | – |")
    out.append("| spec_lib | – | ✓ | – | – |")
    out.append("| haskell | ✓ | ✓✓ | – | ✓✓ |")
    out.append("| c | – | – | ✓✓ | – |")
    out.append("")
    out.append("_(✓✓ = primary fix, ✓ = helps significantly, ○ = helps marginally, – = orthogonal)_")
    out.append("")
    out.append("---")
    out.append("")
    per_type_links = " · ".join(
        f"[{ct}](critical-path-{ct}.md)" for ct in available_cts
    )
    out.append(f"_Per-type details: {per_type_links}_")
    return "\n".join(out) + "\n"


def main() -> int:
    data = json.loads(INPUT.read_text())
    # CSTR enrichment: load duplication scan for case studies + 3rd-party data
    dup_scan_path = REPO / "reports" / "session-duplication-scan.json"
    dup_data = json.loads(dup_scan_path.read_text()) if dup_scan_path.exists() else None

    written: list[str] = []
    available_cts = tuple(ct for ct in CHANGE_TYPE_ORDER if ct in data["change_types"])

    for ct in available_cts:
        out_path = OUT_DIR / f"critical-path-{ct}.md"
        md = render_change_report(ct, data["change_types"][ct], data)
        out_path.write_text(md)
        written.append(str(out_path.relative_to(REPO)))

    summary_path = OUT_DIR / "critical-path-summary.md"
    summary_path.write_text(render_summary_report(data, dup_data))
    written.append(str(summary_path.relative_to(REPO)))

    print("wrote:")
    for p in written:
        print(f"  {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
